/**
 * Context passed to every synthesis rule for evaluation
 */
export interface SynthesisContext {
  /** All tool data from workspace keyed by tool ID */
  tools: Record<string, unknown>;

  /** Workspace metadata */
  meta: {
    companyName: string;
    assessmentDate: string;
  };
}

/**
 * Insight generated by a synthesis rule
 */
export interface Insight {
  /** Unique identifier for this insight instance */
  id: string;

  /** ID of the rule that generated this insight */
  ruleId: string;

  /** Type of insight */
  type: 'gap' | 'strength' | 'warning' | 'opportunity';

  /** Severity level (1=low, 5=critical) */
  severity: 1 | 2 | 3 | 4 | 5;

  /** Short, descriptive title */
  title: string;

  /** Detailed description of the finding */
  description: string;

  /** Actionable recommendation */
  recommendation: string;

  /** IDs of tools that contributed to this insight */
  affectedTools: string[];

  /** Optional additional data for rendering/export */
  data?: Record<string, unknown>;
}

/**
 * Definition of a synthesis rule
 */
export interface SynthesisRule {
  /** Unique rule identifier (e.g., 'E1-execution-capability-gap') */
  id: string;

  /** Human-readable name */
  name: string;

  /** Rule description */
  description: string;

  /** List of tool IDs this rule requires to run */
  requiredTools: string[];

  /** Execute the rule and return any generated insights */
  evaluate: (context: SynthesisContext) => Insight[];

  /** Optional: Calculate dimension scores for synthesis dashboard */
  calculateScores?: (context: SynthesisContext) => Record<string, number>;
}

/**
 * Result of running all synthesis rules
 */
export interface SynthesisResult {
  /** All generated insights, prioritized by severity */
  insights: Insight[];

  /** Calculated scores from rules that provide them */
  scores: Record<string, number>;

  /** Timestamp when synthesis was run */
  timestamp: number;

  /** Number of rules that were evaluated */
  rulesEvaluated: number;

  /** Rules that were skipped due to missing required tools */
  rulesSkipped: string[];
}
