import jsPDF from 'jspdf';
import type { SynthesisResult, Insight } from '@lib/synthesis/types';
import type { PDFSection } from '@types/tool';

interface ReportSection {
  toolId: string;
  toolName: string;
  enabled: boolean;
  data: unknown;
  pdfExport?: PDFSection;
}

interface ReportConfig {
  workspaceName: string;
  companyName: string;
  generatedAt: Date;
  sections: ReportSection[];
  synthesisResult?: SynthesisResult;
  includeInsights: boolean;
}

const COLORS = {
  primary: '#4F46E5',
  secondary: '#6B7280',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  text: '#1F2937',
  lightGray: '#F3F4F6'
};

export async function generatePDFReport(config: ReportConfig): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;

  // Helper functions
  const addPage = () => {
    doc.addPage();
    yPos = margin;
  };

  const checkPageBreak = (neededHeight: number) => {
    if (yPos + neededHeight > pageHeight - margin) {
      addPage();
      return true;
    }
    return false;
  };

  const drawLine = (y: number, color = COLORS.lightGray) => {
    doc.setDrawColor(color);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
  };

  // === COVER PAGE ===
  // Title
  doc.setFontSize(28);
  doc.setTextColor(COLORS.primary);
  doc.text('Business Assessment Report', pageWidth / 2, 60, { align: 'center' });

  // Company name
  doc.setFontSize(18);
  doc.setTextColor(COLORS.text);
  doc.text(config.companyName || 'Your Business', pageWidth / 2, 80, { align: 'center' });

  // Workspace name
  doc.setFontSize(12);
  doc.setTextColor(COLORS.secondary);
  doc.text(`Workspace: ${config.workspaceName}`, pageWidth / 2, 95, { align: 'center' });

  // Generated date
  doc.setFontSize(10);
  doc.text(
    `Generated: ${config.generatedAt.toLocaleDateString()} at ${config.generatedAt.toLocaleTimeString()}`,
    pageWidth / 2,
    105,
    { align: 'center' }
  );

  // Section count
  const enabledSections = config.sections.filter(s => s.enabled);
  doc.setFontSize(11);
  doc.setTextColor(COLORS.text);
  doc.text(`${enabledSections.length} assessment sections included`, pageWidth / 2, 120, { align: 'center' });

  // Insights count
  if (config.includeInsights && config.synthesisResult) {
    const insightCount = config.synthesisResult.insights.length;
    doc.text(`${insightCount} synthesis insights generated`, pageWidth / 2, 130, { align: 'center' });
  }

  // Footer on cover
  doc.setFontSize(8);
  doc.setTextColor(COLORS.secondary);
  doc.text('Generated by VWCGApp - Value-Weighted Capability Gap Assessment', pageWidth / 2, pageHeight - 20, { align: 'center' });

  // === TABLE OF CONTENTS ===
  addPage();
  doc.setFontSize(18);
  doc.setTextColor(COLORS.primary);
  doc.text('Table of Contents', margin, yPos);
  yPos += 15;

  doc.setFontSize(11);
  doc.setTextColor(COLORS.text);
  let tocPage = 3; // Start after cover and TOC

  enabledSections.forEach((section, idx) => {
    doc.text(`${idx + 1}. ${section.toolName}`, margin, yPos);
    doc.text(`Page ${tocPage}`, pageWidth - margin - 20, yPos);
    yPos += 8;
    tocPage++; // Approximate - each section ~1 page
  });

  if (config.includeInsights && config.synthesisResult?.insights.length) {
    yPos += 5;
    doc.text('Synthesis Insights', margin, yPos);
    doc.text(`Page ${tocPage}`, pageWidth - margin - 20, yPos);
  }

  // === ASSESSMENT SECTIONS ===
  for (const section of enabledSections) {
    addPage();

    // Section header
    doc.setFontSize(16);
    doc.setTextColor(COLORS.primary);
    doc.text(section.pdfExport?.title || section.toolName, margin, yPos);
    yPos += 10;

    // Summary
    if (section.pdfExport?.summary) {
      doc.setFontSize(11);
      doc.setTextColor(COLORS.secondary);
      const summaryLines = doc.splitTextToSize(section.pdfExport.summary, contentWidth);
      doc.text(summaryLines, margin, yPos);
      yPos += summaryLines.length * 5 + 5;
    }

    drawLine(yPos);
    yPos += 8;

    // Tables
    if (section.pdfExport?.tables) {
      for (const table of section.pdfExport.tables) {
        checkPageBreak(50);

        // Table header
        doc.setFillColor(COLORS.lightGray);
        doc.rect(margin, yPos - 2, contentWidth, 8, 'F');

        doc.setFontSize(9);
        doc.setTextColor(COLORS.text);
        const colWidth = contentWidth / table.headers.length;

        table.headers.forEach((header, idx) => {
          doc.setFont('helvetica', 'bold');
          doc.text(header, margin + idx * colWidth + 2, yPos + 3);
        });
        yPos += 10;

        // Table rows
        doc.setFont('helvetica', 'normal');
        for (const row of table.rows) {
          checkPageBreak(8);
          row.forEach((cell, idx) => {
            const cellText = doc.splitTextToSize(cell, colWidth - 4);
            doc.text(cellText[0] || '', margin + idx * colWidth + 2, yPos);
          });
          yPos += 6;
        }
        yPos += 5;
      }
    }

    // Insights from this section
    if (section.pdfExport?.insights && section.pdfExport.insights.length > 0) {
      checkPageBreak(30);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(COLORS.text);
      doc.text('Key Findings:', margin, yPos);
      yPos += 7;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      for (const insight of section.pdfExport.insights) {
        checkPageBreak(10);
        const bulletText = `• ${insight}`;
        const lines = doc.splitTextToSize(bulletText, contentWidth - 5);
        doc.text(lines, margin + 3, yPos);
        yPos += lines.length * 5 + 2;
      }
    }
  }

  // === SYNTHESIS INSIGHTS SECTION ===
  if (config.includeInsights && config.synthesisResult?.insights.length) {
    addPage();

    doc.setFontSize(18);
    doc.setTextColor(COLORS.primary);
    doc.text('Synthesis Insights', margin, yPos);
    yPos += 12;

    doc.setFontSize(10);
    doc.setTextColor(COLORS.secondary);
    doc.text(
      `${config.synthesisResult.insights.length} insights from ${config.synthesisResult.rulesEvaluated} analysis rules`,
      margin,
      yPos
    );
    yPos += 10;

    drawLine(yPos);
    yPos += 8;

    // Group insights by type
    const insightsByType: Record<string, Insight[]> = {
      gap: [],
      warning: [],
      opportunity: [],
      strength: []
    };

    config.synthesisResult.insights.forEach(insight => {
      insightsByType[insight.type].push(insight);
    });

    const typeLabels = {
      gap: { label: 'Gaps & Risks', color: COLORS.danger },
      warning: { label: 'Warnings', color: COLORS.warning },
      opportunity: { label: 'Opportunities', color: COLORS.primary },
      strength: { label: 'Strengths', color: COLORS.success }
    };

    for (const [type, insights] of Object.entries(insightsByType)) {
      if (insights.length === 0) continue;

      checkPageBreak(25);

      const typeConfig = typeLabels[type as keyof typeof typeLabels];
      doc.setFontSize(12);
      doc.setTextColor(typeConfig.color);
      doc.setFont('helvetica', 'bold');
      doc.text(`${typeConfig.label} (${insights.length})`, margin, yPos);
      yPos += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(COLORS.text);

      for (const insight of insights) {
        checkPageBreak(25);

        // Severity badge
        const severityLabel = insight.severity >= 4 ? 'HIGH' : insight.severity >= 3 ? 'MED' : 'LOW';
        doc.setFillColor(insight.severity >= 4 ? COLORS.danger : insight.severity >= 3 ? COLORS.warning : COLORS.success);
        doc.roundedRect(margin, yPos - 3, 12, 5, 1, 1, 'F');
        doc.setTextColor('#FFFFFF');
        doc.setFontSize(7);
        doc.text(severityLabel, margin + 2, yPos);

        // Title
        doc.setFontSize(10);
        doc.setTextColor(COLORS.text);
        doc.setFont('helvetica', 'bold');
        doc.text(insight.title, margin + 15, yPos);
        yPos += 6;

        // Description
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        const descLines = doc.splitTextToSize(insight.description, contentWidth - 15);
        doc.text(descLines, margin + 15, yPos);
        yPos += descLines.length * 4 + 3;

        // Recommendation
        doc.setFontSize(8);
        doc.setTextColor(COLORS.secondary);
        const recLines = doc.splitTextToSize(`Recommendation: ${insight.recommendation}`, contentWidth - 15);
        doc.text(recLines, margin + 15, yPos);
        yPos += recLines.length * 4 + 6;
      }
    }
  }

  // === FOOTER ON ALL PAGES ===
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(COLORS.secondary);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  return doc.output('blob');
}

export function getReportFilename(workspaceName: string): string {
  const safeName = workspaceName.replace(/[^a-zA-Z0-9]/g, '_');
  return `VWCGReport_${safeName}.pdf`;
}
