
import React from 'react';
import { useWorkspaceStore } from '../../store/workspaceStore';
import { AdvisorResults } from '../advisor-readiness/AdvisorResults';
import { RoadmapTimeline } from '../roadmap/RoadmapTimeline';
import { SwotMatrix } from '../swot/SwotMatrix';
import { CATEGORIES as ADVISOR_CATEGORIES, QUESTIONS as ADVISOR_QUESTIONS } from '../advisor-readiness/questions';

import {
    BrainCircuit,
    Fingerprint,
    HeartHandshake,
    Target,
    ShieldAlert,
    BookOpen,
    Map as MapIcon,
    ClipboardCheck,
    Lightbulb,
    AlertTriangle,
    Star,
    Zap,
    CheckCircle
} from 'lucide-react';

interface ReportPreviewProps {
    toolIds: string[];
}

// Helper to get icon for insight type
const getInsightIcon = (type: string) => {
    switch (type) {
        case 'risk': return AlertTriangle;
        case 'opportunity': return Star;
        case 'conflict': return Zap;
        case 'strength': return CheckCircle;
        default: return Lightbulb;
    }
};

// Helper to get severity colors
const getSeverityColors = (severity: string) => {
    switch (severity) {
        case 'high': return { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-700', icon: 'text-red-500' };
        case 'medium': return { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-700', icon: 'text-amber-500' };
        case 'low': return { bg: 'bg-green-50', border: 'border-green-200', text: 'text-green-700', icon: 'text-green-500' };
        default: return { bg: 'bg-slate-50', border: 'border-slate-200', text: 'text-slate-700', icon: 'text-slate-500' };
    }
};

export const ReportPreview: React.FC<ReportPreviewProps> = ({ toolIds }) => {
    const { tools, metadata, insights } = useWorkspaceStore();
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    // Helper to calculate Advisor Scores
    const getAdvisorScores = () => {
        const data = tools['advisor-readiness'] || { answers: {} };
        const answers = data.answers || {};
        const scores: Record<string, number> = {};
        const maxScores: Record<string, number> = {};

        ADVISOR_CATEGORIES.forEach(cat => {
            const catQuestions = ADVISOR_QUESTIONS.filter(q => q.category === cat.id);
            scores[cat.id] = catQuestions.reduce((sum, q) => sum + (answers[q.id] || 0), 0);
            maxScores[cat.id] = catQuestions.length * 5;
        });
        return { scores, maxScores };
    };
    const { scores: advisorScores, maxScores: advisorMaxScores } = getAdvisorScores();

    return (
        <div className="bg-white text-slate-800 font-sans">
            {/* Title Page */}
            <div className="min-h-[1000px] flex flex-col items-center justify-center border-b-2 border-slate-100 mb-12 pb-12">
                <div className="w-24 h-24 bg-indigo-600 rounded-2xl flex items-center justify-center mb-8 shadow-xl">
                    <span className="text-white text-4xl font-bold">V</span>
                </div>
                <h1 className="text-5xl font-black text-slate-900 mb-4 text-center">Executive Strategic<br />Report</h1>
                <h2 className="text-2xl text-slate-500 font-medium mb-12">{metadata.name || 'Client Workspace'}</h2>

                <div className="text-center space-y-2">
                    <p className="text-slate-400 font-semibold uppercase tracking-widest text-sm">Generated On</p>
                    <p className="text-xl font-bold text-slate-700">{date}</p>
                </div>
            </div>

            <div className="space-y-16 px-8">
                {/* Executive Insights (Cross-Tool Analysis) */}
                {insights.length > 0 && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-amber-200 pb-2">
                            <Lightbulb className="w-8 h-8 text-amber-600" />
                            <h2 className="text-2xl font-bold text-slate-800">Executive Insights</h2>
                            <span className="ml-auto text-sm text-slate-500 bg-slate-100 px-3 py-1 rounded-full">
                                {insights.length} Strategic {insights.length === 1 ? 'Insight' : 'Insights'}
                            </span>
                        </div>
                        <p className="text-slate-600 mb-6">
                            The following insights were automatically generated by analyzing patterns across your strategic tools.
                        </p>
                        <div className="space-y-4">
                            {insights.map(insight => {
                                const Icon = getInsightIcon(insight.type);
                                const colors = getSeverityColors(insight.severity);
                                return (
                                    <div
                                        key={insight.id}
                                        className={`p-5 rounded-lg border ${colors.bg} ${colors.border}`}
                                    >
                                        <div className="flex items-start gap-3">
                                            <div className={`p-2 rounded-lg ${colors.bg}`}>
                                                <Icon className={`w-5 h-5 ${colors.icon}`} />
                                            </div>
                                            <div className="flex-1">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <h3 className={`font-bold ${colors.text}`}>{insight.title}</h3>
                                                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium uppercase ${
                                                        insight.severity === 'high' ? 'bg-red-100 text-red-600' :
                                                        insight.severity === 'medium' ? 'bg-amber-100 text-amber-600' :
                                                        'bg-green-100 text-green-600'
                                                    }`}>
                                                        {insight.severity}
                                                    </span>
                                                </div>
                                                <p className="text-slate-700 text-sm mb-3">{insight.message}</p>
                                                <div className="bg-white/70 border border-slate-200 rounded-lg p-3">
                                                    <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Recommendation</p>
                                                    <p className="text-sm text-slate-800">{insight.recommendation}</p>
                                                </div>
                                                <div className="mt-2 flex flex-wrap gap-2">
                                                    {insight.relatedTools.map(toolId => (
                                                        <span key={toolId} className="text-xs bg-slate-200 text-slate-600 px-2 py-0.5 rounded">
                                                            {toolId}
                                                        </span>
                                                    ))}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </section>
                )}

                {/* 1. AI Readiness */}
                {toolIds.includes('ai-readiness') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <BrainCircuit className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">AI Readiness Assessment</h2>
                        </div>
                        <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                            {/* Simple text rendering for now as specific chart isn't exported */}
                            <p className="italic text-slate-500">Detailed AI readiness scoring and breakdown.</p>
                        </div>
                    </section>
                )}

                {/* 2. Leadership DNA */}
                {toolIds.includes('leadership-dna') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <Fingerprint className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">Leadership DNA Profile</h2>
                        </div>
                        <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                            <p className="italic text-slate-500">Psychometric profile analysis.</p>
                        </div>
                    </section>
                )}

                {/* 3. BEI */}
                {toolIds.includes('bei') && (
                    <section className="break-before-page break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <HeartHandshake className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">Business Emotional Intelligence</h2>
                        </div>
                        <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                            <h4 className="font-bold text-slate-700 mb-2">Trend Analysis</h4>
                            {tools['bei']?.entries?.length > 1 ? (
                                <p className="text-slate-600">
                                    The organization has recorded {tools['bei'].entries.length} assessment points.
                                    Recent trends indicate {
                                        (tools['bei'].entries[tools['bei'].entries.length - 1].dimensions[0].score >
                                            tools['bei'].entries[0].dimensions[0].score) ? 'positive momentum' : 'stabilization'
                                    } in core emotional competencies.
                                </p>
                            ) : (
                                <p className="text-slate-600">Initial baseline established. Longitudinal data unavailable.</p>
                            )}
                        </div>
                    </section>
                )}

                {/* 4. Vision Canvas */}
                {toolIds.includes('vision-canvas') && tools['vision-canvas'] && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <Target className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">Vision Canvas</h2>
                        </div>
                        <div className="bg-gradient-to-br from-indigo-900 to-slate-900 text-white p-8 rounded-xl shadow-lg">
                            <div className="text-center mb-8">
                                <h3 className="text-indigo-300 uppercase tracking-widest text-xs font-bold mb-2">North Star Metric</h3>
                                <div className="text-3xl font-black">{tools['vision-canvas'].northStar || 'Not Defined'}</div>
                            </div>
                            <div className="grid grid-cols-2 gap-8">
                                <div>
                                    <h4 className="border-b border-indigo-700 pb-2 mb-3 font-semibold text-indigo-200">Strategic Pillars</h4>
                                    <ul className="list-disc list-inside space-y-1 text-sm text-indigo-100">
                                        {(tools['vision-canvas'].pillars || []).map((p: any) => <li key={p.id}>{p.text}</li>)}
                                    </ul>
                                </div>
                                <div>
                                    <h4 className="border-b border-indigo-700 pb-2 mb-3 font-semibold text-indigo-200">Core Values</h4>
                                    <ul className="list-disc list-inside space-y-1 text-sm text-indigo-100">
                                        {(tools['vision-canvas'].values || []).map((v: any) => <li key={v.id}>{v.text}</li>)}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </section>
                )}

                {/* 5. SWOT Analysis */}
                {toolIds.includes('swot') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <ShieldAlert className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">SWOT Analysis</h2>
                        </div>
                        <div className="h-[500px]">
                            <SwotMatrix data={tools['swot'] || {}} />
                        </div>
                    </section>
                )}

                {/* 6. SOP Taxonomy */}
                {toolIds.includes('sop-taxonomy') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <BookOpen className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">SOP Taxonomy</h2>
                        </div>
                        <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                            <p className="italic text-slate-500 mb-4">Process hierarchy structure (Department → Category → Process).</p>
                            {(tools['sop-taxonomy']?.taxonomy || []).length > 0 ? (
                                <div className="space-y-2">
                                    {(tools['sop-taxonomy']?.taxonomy || []).map((dept: any) => (
                                        <div key={dept.id} className="p-3 bg-white border rounded">
                                            <div className="font-bold text-slate-800">{dept.name}</div>
                                            <div className="text-xs text-slate-500 uppercase">{dept.type}</div>
                                            {dept.children?.length > 0 && (
                                                <div className="ml-4 mt-2 space-y-1">
                                                    {dept.children.map((cat: any) => (
                                                        <div key={cat.id} className="text-sm text-slate-600">
                                                            → {cat.name} ({cat.children?.length || 0} processes)
                                                        </div>
                                                    ))}
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <p className="text-slate-400">No taxonomy defined.</p>
                            )}
                        </div>
                    </section>
                )}

                {/* 7. SOP Creation */}
                {toolIds.includes('sop-creation') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <BookOpen className="w-8 h-8 text-emerald-600" />
                            <h2 className="text-2xl font-bold text-slate-800">Created SOPs</h2>
                        </div>
                        <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                            {(tools['sop']?.sops || []).length > 0 ? (
                                <div className="grid grid-cols-2 gap-4">
                                    {(tools['sop']?.sops || []).map((sop: any) => (
                                        <div key={sop.id} className="p-4 border rounded-lg bg-white">
                                            <div className="font-bold text-slate-800">{sop.metadata?.title || sop.title || 'Untitled SOP'}</div>
                                            <div className="text-xs text-slate-500 mt-1">Steps: {sop.steps?.length || 0}</div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <p className="italic text-slate-400">No SOPs have been created yet.</p>
                            )}
                        </div>
                    </section>
                )}

                {/* 8. SOP Management */}
                {toolIds.includes('sop-management') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <BookOpen className="w-8 h-8 text-amber-600" />
                            <h2 className="text-2xl font-bold text-slate-800">SOP Library Status</h2>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            {(tools['sop']?.sops || []).map((sop: any) => (
                                <div key={sop.id} className="p-4 border rounded-lg bg-slate-50">
                                    <div className="font-bold text-slate-800">{sop.metadata.title}</div>
                                    <div className="text-xs text-slate-500 uppercase mt-1">{sop.metadata.status} • {sop.steps.length} Steps</div>
                                </div>
                            ))}
                        </div>
                    </section>
                )}


                {/* 9. Roadmap */}
                {toolIds.includes('roadmap') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <MapIcon className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">90-Day Scaling Roadmap</h2>
                        </div>
                        {/* Force a fixed width/overflow for print */}
                        <div className="overflow-hidden">
                            <RoadmapTimeline tasks={tools['roadmap']?.tasks || []} />
                        </div>
                    </section>
                )}

                {/* 10. Advisor Readiness */}
                {toolIds.includes('advisor-readiness') && (
                    <section className="break-inside-avoid">
                        <div className="flex items-center gap-3 mb-6 border-b border-indigo-100 pb-2">
                            <ClipboardCheck className="w-8 h-8 text-indigo-600" />
                            <h2 className="text-2xl font-bold text-slate-800">Advisor Readiness Profile</h2>
                        </div>
                        <div className="h-[500px]">
                            <AdvisorResults scores={advisorScores} maxScores={advisorMaxScores} />
                        </div>
                    </section>
                )}
            </div>

            <div className="mt-24 pt-12 border-t border-slate-200 text-center text-slate-400 text-sm pb-12">
                &copy; {new Date().getFullYear()} VWCG Unified Application. All Rights Reserved.
            </div>
        </div>
    );
};
