import React, { useState, useRef, useEffect } from 'react';
import { Download } from 'lucide-react';
import { generatePdf } from '../../tools/report/PdfService';
import { useWorkspaceStore } from '../../store/workspaceStore';

interface ExportButtonProps {
    toolName: string;
    renderContent: () => React.ReactNode;
}

export const ExportButton: React.FC<ExportButtonProps> = ({ toolName, renderContent }) => {
    const [isExporting, setIsExporting] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const previewRef = useRef<HTMLDivElement>(null);
    const metadata = useWorkspaceStore(state => state.metadata);

    const handleExport = async () => {
        setIsExporting(true);
        setShowPreview(true);
    };

    useEffect(() => {
        if (showPreview && previewRef.current && isExporting) {
            // Wait for render then export
            const timer = setTimeout(async () => {
                try {
                    const date = new Date().toISOString().split('T')[0];
                    const fileName = `VWCG_${toolName.replace(/\s+/g, '_')}_${date}`;
                    await generatePdf(previewRef.current!, fileName);
                } catch (err) {
                    console.error('Export failed:', err);
                } finally {
                    setIsExporting(false);
                    setShowPreview(false);
                }
            }, 500);
            return () => clearTimeout(timer);
        }
    }, [showPreview, isExporting, toolName]);

    const date = new Date().toLocaleDateString('en-US', { 
        year: 'numeric', month: 'long', day: 'numeric' 
    });

    return (
        <>
            <button
                onClick={handleExport}
                disabled={isExporting}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors text-sm font-medium"
            >
                <Download className="w-4 h-4" />
                {isExporting ? 'Exporting...' : 'Export PDF'}
            </button>

            {/* Hidden render container for PDF generation */}
            {showPreview && (
                <div className="fixed left-[-9999px] top-0">
                    <div 
                        ref={previewRef} 
                        className="bg-white text-slate-800 font-sans"
                        style={{ width: '794px', padding: '40px' }}
                    >
                        {/* Header */}
                        <div className="flex items-center justify-between mb-8 pb-4 border-b-2 border-indigo-600">
                            <div className="flex items-center gap-3">
                                <div className="w-12 h-12 bg-indigo-600 rounded-xl flex items-center justify-center">
                                    <span className="text-white text-xl font-bold">V</span>
                                </div>
                                <div>
                                    <h1 className="text-2xl font-bold text-slate-900">{toolName}</h1>
                                    <p className="text-sm text-slate-500">{metadata.name || 'VWCG Workspace'}</p>
                                </div>
                            </div>
                            <p className="text-sm text-slate-400">{date}</p>
                        </div>

                        {/* Tool Content */}
                        <div className="min-h-[600px]">
                            {renderContent()}
                        </div>

                        {/* Footer */}
                        <div className="mt-8 pt-4 border-t border-slate-200 text-center text-slate-400 text-xs">
                            Generated by VWCG Unified App • {date}
                        </div>
                    </div>
                </div>
            )}
        </>
    );
};
